# Generated by Django 2.0.1 on 2018-01-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tedfile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tedfile',
            name='filename',
        ),
        migrations.AddField(
            model_name='tedfile',
            name='save_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tedfile',
            name='talker_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tedfile',
            name='title',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AddField(
            model_name='tedfile',
            name='video_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tedfile',
            name='video_image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tedfile',
            name='video_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
